name: Build and deploy this site to GitHub Pages

on:
  push:
    branches:
      - master 

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
            
      # Install the correct version of Bundler locally for the user
      - name: Install Bundler 2.4.22 locally
        run: gem install bundler -v 2.4.22 --user-install

      # Ensure that the locally installed Bundler is used
      - name: Add Bundler to PATH
        run: echo "::add-path::$(ruby -e 'print Gem.user_dir')/bin"

      - name: Install dependencies
        run: bundle install

      - uses: jeffreytse/jekyll-deploy-action@v0.4.0
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_baseurl: 'dev-portfolio-blog'
          pre_build_commands: pacman -S --noconfirm nodejs npm
          branch: 'sample-site'
